### ISSUE TITLE
Dots in Table of Contens

### ISSUE THREAD

**Issue by haydarai** [yusufsyaifudin/template-skripsi-mipa#1]
Based on this guide [link](http://luk.staff.ugm.ac.id/riset/panduan/fmipa/PanduanPenulisan.pdf). Table of Contents in Skripsi MIPA UGM shouldn't use dots meanwhile in this template still use dots.

**Comment by yusufsyaifudin** [comment]
thanks for the correction, merged on [ae45d2b](https://github.com/yusufsyaifudin/template-skripsi-mipa/commit/ae45d2b27bbdbfe66238e87b3e4e3bc84a3f9607)
